### ISSUE TITLE
Deleting Images on mobile app

### ISSUE THREAD

**Issue by TheisNiklas** [helmuttheis/XCamera#11]
Deleting of images in the mobile app doesn't seem to work. Tested in UWP app.
When deleting the images will still be there when the app gets started again. Sometimes even a duplicate will be created in the database. The duplicate then got the full image path, with "C:\\users\AppData\..." and not the relative path.
One theory I just had ist, that it could have something to do with the current Status system, but I'm not sure.

**Comment by helmuttheis** [comment]
I have removed the deleted images from the pick list and from the list send to Manager.
These Images are still on the device and in the database, but they are no longer available for the app.

Maybe we should a flag (Include deleted Images) to the config, so that they are available again.
