### ISSUE TITLE
Deleting of project on mobile doesn't work

### ISSUE THREAD

**Issue by TheisNiklas** [helmuttheis/XCamera#3]
Deleting on mobile doesn't work, because the project was opened to check if everything was send.

**Comment by TheisNiklas** [comment]
Idea I just had, maybe add a ".deleted" to the folder name when deleting (maybe also two - at the front to not show it in the projects, I think that function is already there). And check on app startup, if there is a folder with ".deleted" and delete that then.

**Comment by helmuttheis** [comment]
The proposed deferred delete of projects is implemented now.

**Comment by TheisNiklas** [comment]
I have tested it and it works now. closed.
