### ISSUE TITLE
Log spammed with f

### ISSUE THREAD

**Issue by TheisNiklas** [helmuttheis/XCamera#6]
The log in the connect window is spammed with 'f's and doesnt show the logs it should display.

**Comment by helmuttheis** [comment]
Fixed with commit https://github.com/helmuttheis/XCamera/commit/59fc95e205f8f24a6821fa64e3cb233c9a673fa7

**Comment by TheisNiklas** [comment]
The programm was still logging the numbers 1 to 99 with this code: 
`for(int i=0;i<100;i++)
            {
                tbLog.Text += i.ToString() + Environment.NewLine;
            }`
is there a reason for that? (temporarily disabled for latest commit)
